//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CookieMVC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BinaryFile
    {
        public int ID { get; set; }
        public string FileName { get; set; }
        public byte[] FileData { get; set; }
        public long Size { get; set; }
        public string MimeType { get; set; }
    }
}
